name: lint

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run biome check index.ts
